spring.application.name=delivery_vinicola

spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_vinicola
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
